### ISSUE TITLE
Indexing Not Working

### ISSUE THREAD

**Issue by nomaddave** [rayrutjes/wc-order-search-admin#100]
Hi.  Just installed the plugin and setup an account in Algolia.  Set the ID and API keys in the plugin and clicked on "Re-Index Orders".  I expected it to successfully index but it failed giving a very non-descriptive error massage.

I then checked the Algolia account and the wc_orders index was created so I assume the credentials worked but not knowing what else to do I reset the credentials in Algolia and copied them to the plugin settings and saved them.  Tried to "Re-Index Orders" again and still the same error.

As a next step I deactivated and deleted the plugin hoping that would help.  Unfortunately it did not.  So at this point I am stuck.  I am attaching screenshots from both the plugin settings page and the Algolia log file showing both a "post" and "get" transaction.

I hope you can help me get this working.

Thanks!
Dave
![Get Details -Headers](https://user-images.githubusercontent.com/61156955/74674870-0db07f80-5191-11ea-8f52-a0d38593285d.JPG)
![Get Details -Request Body](https://user-images.githubusercontent.com/61156955/74674874-0e491600-5191-11ea-837c-94e481465bca.JPG)
![Post Details - Response Body](https://user-images.githubusercontent.com/61156955/74674875-0ee1ac80-5191-11ea-8f62-d9404c2a66d4.JPG)
![Post Details -Headers](https://user-images.githubusercontent.com/61156955/74674879-0ee1ac80-5191-11ea-9a6d-6df658f7589d.JPG)
![Post Details -Request Body](https://user-images.githubusercontent.com/61156955/74674882-0f7a4300-5191-11ea-8833-68e0f5d5a6a2.JPG)
![Algolia Indices Page - wc_orders Created](https://user-images.githubusercontent.com/61156955/74674883-0f7a4300-5191-11ea-82fc-33e83d111f59.JPG)
![API Keys Settings in Algolia](https://user-images.githubusercontent.com/61156955/74674885-1012d980-5191-11ea-941a-7bbfb629ba02.JPG)
![Error Message on Indexing](https://user-images.githubusercontent.com/61156955/74674887-10ab7000-5191-11ea-8b7d-78eb4b5060e6.JPG)
![Get Details - Response Body](https://user-images.githubusercontent.com/61156955/74674889-11dc9d00-5191-11ea-9775-ada839812398.JPG)

**Comment by rayrutjes** [comment]
Thank you for the very detailed issue.
It seems like most of the 403 errors you shared are happening when you browse the Algolia dashboard.

This plugin does not control how the dashboard behaves.

However, that being said, it seems like you never managed to send over a single order. This might be specific to your website. I think it does not manage to list the orders.

Could you maybe list the plugins you have enabled so I can reproduce when I have some time?

**Comment by nomaddave** [comment]
Hi Raymond,


Thank you very much for your response.  I am not worried about the 403 errors since I am sure those will be resolved if I can ever get the indexing to work.  That is the big issue.  I am using a lot of plugins but I had not thought of those as being a possible problem.  Given that I will check into it myself before bothering you more at this time.  Hopefully it is just a plugin conflict and hopefully it is one that I can do without or you can make to work.  I will keep you posted but it may be a week or 2 (I hope not that long J) so don’t worry if you don’t hear from me right away.   Your plugin is really what I need so I hope I can get it to work.

 

Regards,
Dave

**Comment by nomaddave** [comment]
Hi again, Raymond.  So in my staging environment I changed my theme to a very basic one, I deactivated all but the very essential plugins (Woocommerce), and installed your plugin. I created a completely new account Algolia account to start fresh, copied the credentials and ran Re-Index.  I got the exact same error response.  In Algolia I can see the attempt to access it from the API.  An index was create (just as before) so the credentials at some level must be working.  This time I am sending you logs from the Algolia system as well as the "Indices/Configuration" screen.  In the configuration screen the attributes match exactly the API Call Detail - Request Body (which since it is the "request" I assume it is what your plugin is sending).  However, if you look at the bottom of the configuration screen (image included) it says "We couldn't find the attribute **id** in a small sample of your records; there might be a typo."  So as a debugging step I tried deleting the "ID" attribute in the configuration.  When doing that the message at the bottom simply changed to say "We couldn't find the attribute **number** in a small sample of your records; there might be a typo." So something is not right. Also included a list of the plugins still active while testing.

I hope this additional information will be helpful to you.
![API Call Detail - Request Body 3](https://user-images.githubusercontent.com/61156955/74858707-8e53b500-5324-11ea-9802-bccc50277fd4.JPG)
![API Call Detail - Request Body 2](https://user-images.githubusercontent.com/61156955/74858712-8f84e200-5324-11ea-98b7-082e212c2966.JPG)
![API Call Detail - Request Body 1](https://user-images.githubusercontent.com/61156955/74858713-901d7880-5324-11ea-9d9d-9dda76e550bd.JPG)
![Searchable Attributes 2](https://user-images.githubusercontent.com/61156955/74858717-901d7880-5324-11ea-93fc-286e7aa9fdf9.JPG)
![Searchable Attributes 1](https://user-images.githubusercontent.com/61156955/74858720-90b60f00-5324-11ea-899d-a0355bc35c34.JPG)
![API Call Detail - Header](https://user-images.githubusercontent.com/61156955/74858721-914ea580-5324-11ea-8611-90b21a9569f4.JPG)
![API Call Detail - Response Body 1](https://user-images.githubusercontent.com/61156955/74858722-914ea580-5324-11ea-9687-b106d2c0e10e.JPG)
![Plugins](https://user-images.githubusercontent.com/61156955/74859151-3a959b80-5325-11ea-9616-211bdd2e4865.JPG)
