### ISSUE TITLE
Record quota exceeded

### ISSUE THREAD

**Issue by Goodzco** [rayrutjes/wc-order-search-admin#23]
Hi, 
I was trying this plugin with a free plan, but when quota on algolia was full i got this message : 

`Uncaught WC_Order_Search_Admin\AlgoliaException: Record quota exceeded, change plan or delete records. in /home/***/public_html/wp-content/plugins/wc-order-search-admin/libs/algolia/algoliasearch-client-php/src/WC_Order_Search_Admin/Client.php:992`

The problem is that all the website was unavailable due to this error and no order was made...

**Comment by rayrutjes** [comment]
Very sorry about that @Goodzco ,

Will implement a fix right away.

Thanks for reporting it!

**Comment by rayrutjes** [comment]
@Goodzco I implemented a fix here: #24 

Before merging, can you confirm that the errors only displayed when actually editing or interacting with an order?

You say that all the website was unavailable, so I fear I miss something here.

**Comment by rayrutjes** [comment]
You can now update to version 1.1.1 which should not longer block your website.
I would highly appreciate if you could confirm it works.

**Comment by jfretin** [comment]
@rayrutjes I am one of the backend dev for @Goodzco project. The uncaught Algolia exception was breaking the chain of hooks on order save. So we lost customer orders between the time we exceeded quota and the time we saw the problem. Only a new entry in posts table was created, and that's all.

We migrated to a paid Algolia plan, but seeing your change in the commit, all should go smoothly from now ;)

Thanks!

**Comment by rayrutjes** [comment]
I'm sorry for the struggle @jfretin!
Let me know if there is anything else I can help you with in the future!

**Comment by rayrutjes** [comment]
BTW I'd love to have your feedback on the plugin. 
I'd love to hear:
- how you found it
- what problem you where looking to solve
- if it solved the problem ;)

In any case, a [review for future users is more than welcome here](https://wordpress.org/support/plugin/wc-order-search-admin/reviews/).
