### ISSUE TITLE
change id and match the number within the consecutive order ...

### ISSUE THREAD

**Issue by C0rporeus** [rayrutjes/wc-order-search-admin#97]
![agnolia](https://user-images.githubusercontent.com/14317273/68057162-19039c00-fcc3-11e9-9e39-0989a06b9977.png)

I implemented the solution yesterday, my orders coincided with the id number, but from the indexing with agnolia this property was lost and now without different, this makes the traceability with the payment gateway becomes more complex, so I ended up obstructing the application before improving it ...

**Comment by rayrutjes** [comment]
Hello @C0rporeus ,

I'm not sure I fully understand your flow.

It seems that your order changes number after indexing?

**Comment by C0rporeus** [comment]
Yes, the orders already bring a successive order, however after using the tool this order changed as specific in the graph, how can I fix it from its solution?

> 
> 
> Hello @C0rporeus ,
> 
> I'm not sure I fully understand your flow.
> 
> It seems that your order changes number after indexing?

Yes, the orders already bring a successive order, however after using the tool this order changed as specific in the graph, how can I fix it from its solution?

**Comment by rayrutjes** [comment]
Is there an easy way to reproduce the issue?
