### ISSUE TITLE
Not working any more

### ISSUE THREAD

**Issue by inventosmateros** [rayrutjes/wc-order-search-admin#99]
Hello!
Love the plugin but stopped working a few days ago.
Woocommerce: Versión 3.9.1
Wordpress  versión 5.3.2–es_AR

Thanks!

**Comment by rayrutjes** [comment]
Thanks for reporting the issue,

do you have any errors we could work with?

What isn't working? The search in the frontend or the indexing or the backend search?

**Comment by rayrutjes** [comment]
I'm closing as it seems no other users are experiencing problems currently.
Feel free to re-open with context so I can help you.
